### ISSUE TITLE
Crash at load time on MacOS 10.15.5 (Catalina) from 0.3.0 release

### ISSUE THREAD

**Issue by vielmetti** [hmatuschek/qdmr#4]
Crash when loading the software from the provided DMG, error reads in part

```
  Reason: Incompatible library version: qdmr requires version 5.13.0 or later, but QtWidgets provides version 5.12.0
```

I upgraded the Qt that comes with homebrew (brew upgrade qt5) but it doesn't seem to be the version that's getting picked up by qdmr.

**Comment by vielmetti** [comment]
The 0.2.3 release does load onto my system, so this is a regression in 0.3.0.

**Comment by hmatuschek** [comment]
The DMG comes with all libraries included (it is therefore quiet big). I believe that this was a missing option on the macdeployqt call, so the DMG was distributed with some old libraries. I released a bug-fix version 0.3.1 that should fix it.  Let me know whether it works for you.

**Comment by vielmetti** [comment]
0.3.1 release is crashing at load, with this (different) error

```
Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: __ZN14FileLogHandlerC1ERK7QStringN10LogMessage5LevelEP7QObject
  Referenced from: /private/var/folders/*/QDMR.app/Contents/MacOS/qdmr
  Expected in: /private/var/folders/*/QDMR.app/Contents/MacOS/../Frameworks/libdmrconf.0.3.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                          	0x0000000115c67ebe __abort_with_payload + 10
1   dyld                          	0x0000000115c9151d abort_with_payload_wrapper_internal + 80
2   dyld                          	0x0000000115c9154f abort_with_payload + 9
3   dyld                          	0x0000000115c8ebd2 dyld::halt(char const*) + 463
4   dyld                          	0x0000000115c16b01 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 140
5   libdyld.dylib                 	0x00007fff723d0692 dyld_stub_binder + 282
6   ???                           	0x000000010eadc308 0 + 4541235976
7   com.github.hmatuschek.qdmr    	0x000000010ea4b745 Application::Application(int&, char**) + 37
8   com.github.hmatuschek.qdmr    	0x000000010ea4a976 main + 214
9   libdyld.dylib                 	0x00007fff723d1cc9 start + 1
```

**Comment by hmatuschek** [comment]
Oh, that is weird. I'll have a look at it.

**Comment by hmatuschek** [comment]
I've uploaded a rebuild of the DMG labeled "0.3.1-1". I hope that fixes the issue.

**Comment by amboman** [comment]
Issue seems to still persist on the same version of Mac OS X. Any ideas of what else to try?

**Comment by hmatuschek** [comment]
Ok, I updated my Qt libraries and rebuild everything for the 0.4.0 release. If this does not work, I have absolutely no clue.

**Comment by hmatuschek** [comment]
Version 0.4.1 has been verified to work under Mac OS X Catalina 10.15.7.
